# This workflow will check out the code, install node dependencies, and print the diff
name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2 # Fetch the last 2 commits for the diff
    - name: Show git diff
      run: git diff HEAD^ HEAD
